name: Deploy on Azure

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install packages
        run: |
          sudo apt-get update
          sudo apt-get upgrade
          sudo apt-get install -y nodejs npm imagemagick
          npm install
      - name: Generate caching artifacts
        run: |
          npx live-server src --port=8000 &
          sleep 5
          node src/takeScreenshot.cjs
          convert -append part*.png screenshot_old.png
          rm -rf part*.png
      - name: Prerender and minify HTML
        run: |
          node src/fillContent.js > src/index2.html
          pushd src
          node postprocess.cjs > index.html
          popd
      - name: Generate and compare screenshot
        run: |
          sleep 5
          node src/takeScreenshot.cjs nocache
          convert -append part*.png screenshot_new.png
          rm -rf part*.png
          result=$(compare -metric RMSE screenshot_old.png screenshot_new.png diff.png 2>&1)
          echo "Difference: $result"
          rmse=$(echo "$result" | cut -d' ' -f1)
          if [ "$rmse" -ne '0' ]; then
            echo q"Images do not match! Failing the job."
            exit 1
          fi
      - name: Remove unused files
        run: |
          rm src/.prettierrc
          rm src/input.css
          rm src/output.css
          rm -rf src/data
          rm -rf src/font
          rm src/fillContent.js
          rm src/resources.js
          rm src/generateLatex.js
          rm src/takeScreenshot.cjs
          rm src/postprocess.js
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Upload to blob storage
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob delete-batch --account-name myresume1913 --source '$web' --auth-mode key
            az storage blob upload-batch --account-name myresume1913  --auth-mode key -d '$web' --overwrite -s 'src'

      - name: Purge CDN endpoint
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az cdn endpoint purge --content-paths  "/*" --profile-name "resume-static-website" --name "resumestaticwebsite2" --resource-group "resume_website"

        # Azure logout
      - name: logout
        run: |
          az logout
        if: always()
