name: Deploy on Azure

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Upload to blob storage
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob upload-batch --account-name myresume1913  --auth-mode key -d '$web' --overwrite -s 'src'
      - name: Purge CDN endpoint
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az cdn endpoint purge --content-paths  "/*" --profile-name "resume-static-website" --name "resumestaticwebsite2" --resource-group "resume_website"

        # Azure logout
      - name: logout
        run: |
          az logout
        if: always()
