name: Deploy on Azure

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install packages
        run: |
          sudo apt-get install nodejs npm
          npm install
      - name: Generate caching artifacts
        run: |
          npx http-server src -p 8000 &
          node src/takeScreenshot.cjs
      - name: Prerender HTML
        run: |
          node src/fillContent.js > src/index2.html
          mv src/index2.html src/index.html
      - name: Remove unused files
        run: |
          rm src/.prettierrc
          rm src/fillContent.js
          rm src/userDetails.js
          rm src/resources.js
          rm src/projects.js
          rm src/generateLatex.js
          rm src/takeScreenshot.cjs
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Upload to blob storage
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob delete-batch --account-name myresume1913 --source '$web' --auth-mode key
            az storage blob upload-batch --account-name myresume1913  --auth-mode key -d '$web' --overwrite -s 'src'

      - name: Purge CDN endpoint
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az cdn endpoint purge --content-paths  "/*" --profile-name "resume-static-website" --name "resumestaticwebsite2" --resource-group "resume_website"

        # Azure logout
      - name: logout
        run: |
          az logout
        if: always()
