name: Compile and upload resume

on:
    push:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Generate LaTeX
              run: |
                sudo apt-get install nodejs
                node src/generateLatex.js > resume.tex
            - name: Compile LaTeX
              uses: xu-cheng/latex-action@v3
              with:
                root_file: resume.tex
            - name: Upload PDF
              uses: actions/upload-artifact@v3
              with:
                name: Resume
                path: resume.pdf
            - name: Get current date
              id: date
              run: echo "::set-output name=date::$(date +'%Y.%m.%d_%H.%M.%S')"
            - name: Release Resume
              uses: softprops/action-gh-release@v1
              with:
                files: |
                    resume.pdf
                body: "Resume generated at ${{ steps.date.outputs.date }}"
                tag_name: ${{ steps.date.outputs.date }}