name: Compile and upload resume

on:
    push:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Install packages
              run: |
                sudo apt-get update
                sudo apt-get upgrade
                sudo apt-get -y install nodejs npm imagemagick
                npm install
            - name: Generate LaTeX
              run: |
                node src/generateLatex.js > resume.tex
            - name: Compile LaTeX
              uses: xu-cheng/latex-action@v3
              with:
                root_file: resume.tex
            - name: Generate screenshots
              run: |
                npx http-server src -p 8000 &
                node src/takeScreenshot.cjs
                convert -append *.png screenshot.jpg
                convert part0.png -resize 1200x750 thumbnail.jpg
            - name: Upload PDF and screenshots
              uses: actions/upload-artifact@v4
              with:
                name: ResumeAndScreenshot
                path: |
                  resume.pdf
                  screenshot.jpg
                  thumbnail.jpg
            - name: Get current date
              id: date
              run: echo "date=$(date +'%Y.%m.%d_%H.%M.%S')" >> $GITHUB_ENV
            - name: Release PDF and screenshots
              uses: softprops/action-gh-release@v2
              with:
                files: |
                    resume.pdf
                    screenshot.jpg
                    thumbnail.jpg
                body: "Artifacts generated at ${{ env.date }}"
                tag_name: ${{ env.date }}
